---
- name: Installation du serveur
  hosts: web
  remote_user: "{{ user }}"
  tasks:
  - name: DEPLOY | Install rsync 
    become: true
    become_user: root
    apt: 
      update_cache: yes
      name: rsync
      state: present
  - include_vars:
      file: ansible/vars.yml
  - include_role:
      name: ansistrano.deploy