---
- name: Installation du serveur
  hosts: web
  remote_user: root
  tasks:
    - include_vars:
        file: ansible/vars.yml
    - name: "USER | Creation de {{ user }}"
      user:
        name: "{{ user }}"
        shell: /bin/bash
    - name: USER | Clef SSH
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: "USER | Sudoers {{ user }}"
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^{{ user }}"
        line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
    - name: APT | Update & Upgrade
      apt:
        upgrade: dist
        update_cache: yes
    - name: Creates directory
      file:
        path: /src/www/e-commerce
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes
    - include_role:
        name: ansible/tools
    - include_role:
        name: ansible/php
    - include_role:
        name: ansible/apache
    - include_role:
        name: ansible/nodejs
    - name: REDIS | Install
      apt:
        name: redis-server
        state: present
    - name: GIT | Create git brut repository
      command: "git init --bare {{ ansistrano_deploy_to }}.git"
      args:
        creates: "{{ ansistrano_deploy_to }}.git"
      become: true
      become_user: "{{ user }}"
- import_playbook: deploy.yml
