---
- name: PHP | Downloading php8.0 key
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
- name: PHP | Add debian source for php 8.0
  shell: | 
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" |tee /etc/apt/sources.list.d/php.list
    apt update
- name: PHP | Install
  apt:
    update_cache: yes
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-pdo"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "libapache2-mod-php{{ php_version }}"
      - libapache2-mod-fcgid
    state: present
- name: PHP | Give right to php8.0-fpm
  shell: | 
    a2enmod proxy_fcgi setenvif
    a2enconf php8.0-fpm
- name: PHP | Composer
  shell: | 
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      php -r "unlink('composer-setup.php');"

- name: PHP | Disable Errors
  lineinfile: 
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "display_errors ="
    line: "display_errors = 0"
  notify: php restart
      # wget https://get.symfony.com/cli/installer -O - | bash
      # mv /root/.symfony/bin/symfony /usr/local/bin/symfony
