apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: backend-deployment-staging
  namespace: yep-staging
  labels:
    app: backend-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-staging
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend-staging
    spec:
      restartPolicy: Always
      containers:
      - name: backend-staging
        image: docker.io/wbarmis/sutoremon_tv:backend
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: backend-service-staging
  namespace: yep-staging
spec:
  type: LoadBalancer
  selector:
    app: backend-staging
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001