apiVersion: v1
kind: Namespace
metadata:
  name: yep-staging
---
apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: frontend-deployment-staging
  namespace: yep-staging
  labels:
    app: frontend-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-staging
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend-staging
    spec:
      restartPolicy: Always
      containers:
      - name: frontend-staging
        image: docker.io/wbarmis/sutoremon_tv:frontend
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: frontend-service-staging
  namespace: yep-staging
spec:
  type: LoadBalancer
  selector:
    app: frontend-staging
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000