apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: stream-deployment-staging
  namespace: yep-staging
  labels:
    app: stream-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stream-staging
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stream-staging
    spec:
      restartPolicy: Always
      containers:
      - name: stream-staging
        image: docker.io/wbarmis/sutoremon_tv:stream
        ports:
        - containerPort: 8003
        - containerPort: 1935
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: stream-service-front-staging
  namespace: yep-staging
spec:
  type: LoadBalancer
  selector:
    app: stream-staging
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: stream-service-stream-staging
  namespace: yep-staging
spec:
  type: LoadBalancer
  selector:
    app: stream-staging
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
