---
- name: Installation du serveur
  hosts: production
  remote_user: root
  tasks:
  - name: "USER | Creation de {{ user }}"
    user: 
      name: "{{ user }}"
      shell: /bin/bash
  - name: USER | Clef SSH
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: "USER | Sudoers {{ user }}"
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^{{ user }}"
      line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  - name: APT | Update & Upgrade
    apt:
      upgrade: dist
      update_cache: yes
  - name: APT | Install rsync 
    become: true
    become_user: root
    apt: 
      update_cache: yes
      name: rsync
      state: present
  # - include_role:
  #     name: role/tools
  # - include_role:
  #     name: role/php
  # - include_role:
  #     name: role/apache
  # - include_role:
  #     name: role/nodejs
- import_playbook: deploy.yml