apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: backend-deployment-prod
  namespace: yep-prod
  labels:
    app: backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-prod
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend-prod
    spec:
      restartPolicy: Always
      containers:
      - name: backend-prod
        image: docker.io/wbarmis/sutoremon_tv:backend1
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: backend-service-prod
  namespace: yep-prod
spec:
  type: LoadBalancer
  selector:
    app: backend-prod
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001