apiVersion: v1
kind: Namespace
metadata:
  name: yep-prod
---
apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: frontend-deployment-prod
  namespace: yep-prod
  labels:
    app: frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-prod
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend-prod
    spec:
      restartPolicy: Always
      containers:
      - name: frontend-prod
        image: docker.io/wbarmis/sutoremon_tv:frontend1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: frontend-service-prod
  namespace: yep-prod
spec:
  type: LoadBalancer
  selector:
    app: frontend-prod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000