apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: stream-deployment-prod
  namespace: yep-prod
  labels:
    app: stream-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stream-prod
  template:
    metadata:
      labels:
        app: stream-prod
    spec:
      restartPolicy: Always
      containers:
      - name: stream-prod
        image: wbarmis/sutoremon_tv:stream
        ports:
        - containerPort: 8003
        - containerPort: 1935
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: stream-service-front-prod
  namespace: yep-prod
spec:
  type: LoadBalancer
  selector:
    app: stream-prod
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: stream-service-stream-prod
  namespace: yep-prod
spec:
  type: LoadBalancer
  selector:
    app: stream-prod
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
