apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: test-deployment-prod
  namespace: yep-prod
  labels:
    app: test-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-prod
  template:
    metadata:
      labels:
        app: test-prod
    spec:
      restartPolicy: Always
      containers:
      - name: test-prod
        image: docker.io/wbarmis/sutoremon_tv:frontend1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: test-service-prod
  namespace: yep-prod
spec:
  type: ClusterIP
  selector:
    app: test-prod
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 3000